/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AvFFzkIkir8
 */
"use client"

import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"

import { useGlobalContext } from "@/context/store";

export default function componentsShowcase() {

  const {colors, shadow, border} = useGlobalContext();

  const boxShadowStyle = {
    boxShadow: `${shadow.x}px ${shadow.y}px ${shadow.blur}px ${shadow.spread}px ${colors.accent} ${shadow.inset ? 'inset ' : ''}`
  }

  const borderStyle = {
    border: `${border.width}px ${border.style} ${colors.accent}`,
    ...(border.radius > 0 && { borderRadius: `${border.radius}px` }),
  }

  return (
    <section key="1" className="p-8 mt-20">
      <div className="grid grid-cols-3 gap-6">
        <Card style={{...borderStyle, ...boxShadowStyle}}>
          <CardHeader>
            <CardTitle>Card Title</CardTitle>
            <CardDescription>This is a card description.</CardDescription>
          </CardHeader>
          <CardContent>Card Content</CardContent>
          <CardFooter>
            <Button style={{backgroundColor: colors.primary}}>Card Button</Button>
          </CardFooter>
        </Card>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline"  style={{...borderStyle, ...boxShadowStyle}}>Open</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent className="w-56">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuGroup>
              <DropdownMenuItem>Profile</DropdownMenuItem>
              <DropdownMenuItem>Billing</DropdownMenuItem>
            </DropdownMenuGroup>
          </DropdownMenuContent>
        </DropdownMenu>
        <Card style={{...borderStyle, ...boxShadowStyle}}>
          <CardHeader>
            <CardTitle>Input Fields</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              <Label htmlFor="text-input">Text Input</Label>
              <Input id="text-input" placeholder="Enter text here" type="text" />
            </div>
            <div className="grid grid-cols-2 gap-4 items-center">
              <div className="space-y-1 flex flex-col items-start">
                <div className="flex items-center space-x-2">
                  <Label htmlFor="checkbox">Checkbox</Label>
                  <Input id="checkbox" type="checkbox" />
                </div>
                <div className="flex items-center space-x-2">
                  <Label htmlFor="toggle">Toggle</Label>
                  <Input className="toggle" id="toggle" type="checkbox" />
                </div>
              </div>
              <div className="space-y-1">
                <Label htmlFor="slider">Slider</Label>
                <Input defaultValue="50" id="slider" max="100" min="0" type="range" />
                <Label htmlFor="file">File</Label>
                <Input id="file" type="file" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Tabs className="w-full border border-gray-200 rounded-lg" defaultValue="tab1" style={{...borderStyle, ...boxShadowStyle}}>
          <TabsList className="flex gap-2" style={{backgroundColor: colors.secondary}}>
            <TabsTrigger value="tab1">Tab 1</TabsTrigger>
            <TabsTrigger value="tab2">Tab 2</TabsTrigger>
          </TabsList>
          <TabsContent value="tab1">
            <p>Tab 1 Content</p>
          </TabsContent>
          <TabsContent value="tab2">
            <p>Tab 2 Content</p>
          </TabsContent>
        </Tabs>
        <Card style={{...borderStyle, ...boxShadowStyle}}>
          <CardHeader>
            <CardTitle>Colors Showcase</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <Button style={{backgroundColor: colors.primary}}>Primary Color</Button>
            <Button style={{backgroundColor: colors.secondary}}>Secondary Color</Button>
            <Button style={{backgroundColor: colors.accent}}>Accent Color</Button>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-r from-purple-400 via-pink-500 to-red-500"
          style={{...borderStyle, ...boxShadowStyle, background: `linear-gradient(to right, ${colors.primary}, ${colors.secondary})`}}
        />
      </div>
    </section>
  )
}
