/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gyb84pI4pkQ
 */
"use client"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Button } from "@/components/ui/button"

import { useGlobalContext } from "@/context/store";

export default function dashboardExample() {
  const {colors, fonts, shadow, border} = useGlobalContext();

  const dynamicStyle = {
    boxShadow: `${shadow.x}px ${shadow.y}px ${shadow.blur}px ${shadow.spread}px ${colors.accent} ${shadow.inset ? 'inset ' : ''}`,
    border: `${border.width}px ${border.style} ${colors.accent}`,
    ...(border.radius > 0 && { borderRadius: `${border.radius}px` }),
  }

  return (
    <div className="flex p-8 mt-20">
      <aside className="w-64">
        <div
          className="flex items-center justify-center h-14 border-b"
        >
          <h2
            className="text-2xl font-semibold"
            style={{fontFamily: fonts.header}}
          >
            Dashboard
          </h2>
        </div>
        <ul className="mt-2">
          <li className="mt-8">
            <Link className="flex" href="#">
              <LayoutDashboardIcon className="h-5 w-5" />
              <span className="mx-4 font-medium">Dashboard</span>
            </Link>
          </li>
          <li className="mt-8">
            <Link className="flex" href="#">
              <PieChartIcon className="h-5 w-5" />
              <span className="mx-4 font-medium">Analytics</span>
            </Link>
          </li>
          <li className="mt-8">
            <Link className="flex" href="#">
              <UsersIcon className="h-5 w-5" />
              <span className="mx-4 font-medium">Users</span>
            </Link>
          </li>
          <li className="mt-8">
            <Link className="flex" href="#">
              <SettingsIcon className="h-5 w-5" />
              <span className="mx-4 font-medium">Settings</span>
            </Link>
          </li>
          <li className="mt-8">
            <Link className="flex" href="#">
              <HelpCircleIcon className="h-5 w-5" />
              <span className="mx-4 font-medium">Support</span>
            </Link>
          </li>
        </ul>
      </aside>
      <main className="flex-1 p-10">
        <header className="flex justify-between items-center">
          <h2 
            className="text-2xl font-semibold"
            style={{fontFamily: fonts.header}}
          >
            Dashboard
          </h2>
          <div className="relative">
            <SearchIcon className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
            <Input
              className="pl-10 pr-4 rounded-md h-10"
              placeholder="Search users..."
              type="search"
              style={dynamicStyle}
            />
          </div>
        </header>
        <section className="grid gap-8 mt-8 md:grid-cols-2 lg:grid-cols-4">
          <Card style={dynamicStyle}>
            <CardHeader className="flex items-center justify-between">
              <CardTitle
               style={{fontFamily: fonts.header}}
              >
                Revenue
              </CardTitle>
              <DollarSignIcon className="h-5 w-5" />
            </CardHeader>
            <CardContent>
              <div
                className="text-2xl font-bold"
                style={{color: colors.primary}}
              >
                $45,231.89
              </div>
              <p
                className="text-xs"
                style={{color: colors.primary}}
              >
                +20.1% from last month
              </p>
            </CardContent>
          </Card>
          <Card style={dynamicStyle}>
            <CardHeader className="flex items-center justify-between">
              <CardTitle
               style={{fontFamily: fonts.header}}
              >
                Active Users
              </CardTitle>
              <UsersIcon className="h-5 w-5" />
            </CardHeader>
            <CardContent>
              <div
                className="text-2xl font-bold"
                style={{color: colors.primary}}
              >
                +2350
              </div>
              <p
                className="text-xs"
                style={{color: colors.primary}}
              >
                +180.1% from last month
              </p>
            </CardContent>
          </Card>
          <Card style={dynamicStyle}>
            <CardHeader className="flex items-center justify-between">
              <CardTitle
               style={{fontFamily: fonts.header}}
              >
                Subscription Plans
              </CardTitle>
              <CreditCardIcon className="h-5 w-5" />
            </CardHeader>
            <CardContent>
              <div
                className="text-2xl font-bold"
                style={{color: colors.primary}}
              >
                +12,234
              </div>
              <p
                className="text-xs"
                style={{color: colors.primary}}
              >
                +19% from last month
              </p>
            </CardContent>
          </Card>
          <Card style={dynamicStyle}>
            <CardHeader className="flex items-center justify-between">
              <CardTitle
               style={{fontFamily: fonts.header}}
              >
                Support Tickets
              </CardTitle>
              <HelpCircleIcon className="h-5 w-5" />
            </CardHeader>
            <CardContent>
              <
                div className="text-2xl font-bold"
                style={{color: colors.primary}}
              >
                +573
              </div>
              <p
                className="text-xs"
                style={{color: colors.primary}}
              >
                +201 since last hour
              </p>
            </CardContent>
          </Card>
        </section>
        <section className="mt-8">
          <Card 
            style={dynamicStyle}
          >
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead
                    style={{fontFamily: fonts.header}}
                  >
                    Name
                  </TableHead>
                  <TableHead
                    style={{fontFamily: fonts.header}}
                  >
                    Email
                  </TableHead>
                  <TableHead
                    style={{fontFamily: fonts.header}}
                  >
                    Subscription
                  </TableHead>
                  <TableHead
                    style={{fontFamily: fonts.header}}
                  >
                    Actions
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>John Doe</TableCell>
                  <TableCell>john@example.com</TableCell>
                  <TableCell>Premium</TableCell>
                  <TableCell>
                    <Button
                      size="sm"
                      variant="outline"
                      style={dynamicStyle}
                    >
                      Edit
                    </Button>
                    <Button
                      className="ml-2"
                      size="sm"
                      variant="outline"
                      style={{...dynamicStyle, backgroundColor: colors.secondary}}
                    >
                      Delete
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Jane Doe</TableCell>
                  <TableCell>jane@example.com</TableCell>
                  <TableCell>Basic</TableCell>
                  <TableCell>
                    <Button
                      size="sm"
                      variant="outline"
                      style={dynamicStyle}
                    >
                      Edit
                    </Button>
                    <Button
                      className="ml-2"
                      size="sm"
                      variant="outline"
                      style={{...dynamicStyle, backgroundColor: colors.secondary}}
                    >
                      Delete
                    </Button>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Bob Smith</TableCell>
                  <TableCell>bob@example.com</TableCell>
                  <TableCell>Free</TableCell>
                  <TableCell>
                    <Button
                      size="sm"
                      variant="outline"
                      style={dynamicStyle}
                    >
                      Edit
                    </Button>
                    <Button
                      className="ml-2"
                      size="sm"
                      variant="outline"
                      style={{...dynamicStyle, backgroundColor: colors.secondary}}
                    >
                      Delete
                    </Button>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Card>
        </section>
      </main>
    </div>
  )
}


function LayoutDashboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>
  )
}


function PieChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function HelpCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function CreditCardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}
